### ISSUE TITLE
Second review comments

### ISSUE THREAD

**Issue by raghuprathap** [sanzacha/final-capsule-project-app#2]
1). Create a Readme.MD file with all instructions to install, test, run application.
2). after `npm run serve` hitting browser URL with `localhost:3000` making network calls to 
`https://final-capsule-project-app.herokuapp.com/users`
![image](https://user-images.githubusercontent.com/3498847/45340376-f476cd00-b5b3-11e8-86de-c61557dea3fa.png)
3). Even after browsing `https://final-capsule-project-app.herokuapp.com/` after logging in network calls are throwing 404 not found error. Please check below screenshot.
![image](https://user-images.githubusercontent.com/3498847/45340429-2ab44c80-b5b4-11e8-9660-8dfe293f1530.png)
4). Configure eslint with airbnb. 
5). Write unit test cases for React components. 
6). Implement Sagas to send / Recieve messages.
7). Heroku deployed app not working after logging in throwing 404 not found error.

**Comment by sanzacha** [comment]
Hi @raghuprathap,
Below points fixed.

- Readme.MD file updated
- Network call fixed
- Heroku deployment is success but getting authentication error in pusher chatKit.

**Comment by sanzacha** [comment]
Hi @raghuprathap ,

Configured eslint with airbnb. Some of the ESLint error needs to fix. I am working on that.

**Comment by sanzacha** [comment]
@raghuprathap - Heroku app issue fixed

**Comment by sanzacha** [comment]
@raghuprathap - Sagas to send / Recieve messages implimented

**Comment by sanzacha** [comment]
@raghuprathap - ESLint implemented and errors fixed

**Comment by sanzacha** [comment]
@raghuprathap - Test cases are pending, Bit busy with project. Please close this issue.

**Comment by sanzacha** [comment]
Code re-factored with review comments, so I am closing this issue. Test cases pending.
