### ISSUE TITLE
Review Comments 

### ISSUE THREAD

**Issue by ruchik-gaikwad** [sanzacha/final-capsule-project-app#3]
![screenshot from 2018-09-14 11-03-09](https://user-images.githubusercontent.com/22982710/45531572-00f66200-b80e-11e8-88b8-7b054627c52d.png)

Tried using the deployed application: 
1. After entering the username, it shows loading nothing seems to happen after that attaching the screenshot for the refrence

**Comment by sanzacha** [comment]
![image](https://user-images.githubusercontent.com/40419990/45551190-b0e9c080-b84a-11e8-8718-200d7320b51a.png)

@ruchik-gaikwad  - It's working for me. Attached screenshot for your reference.

**Comment by sanzacha** [comment]
@ruchik-gaikwad - Sorry, It is not working properly. I will be fixing this issue. Please wait for my next update.

**Comment by sanzacha** [comment]
@ruchik-gaikwad - Issue is fixed. Please review. I am closing this issue.
