### ISSUE TITLE
Functional review

### ISSUE THREAD

**Issue by raghuprathap** [sanzacha/final-capsule-project-app#4]
Logout option need to be there.
Once login if page is refreshed user is getting logged out.
One-on-One chat is not possible but only room chat/channel chat.
There should be an option to create room by user and add people to it.

**Comment by sanzacha** [comment]
hi @raghuprathap 
Below points done and pushed. Rest I am working.

1. Logout option need to be there.
2. Once login if page is refreshed user is getting logged out.

**Comment by sanzacha** [comment]
Hi @raghuprathap ,
Create Room functionality implemented
